name: CronBot

on:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

    steps:
      - uses: actions/checkout@v2
      - name: grow grass
        run: |
          bash  ./scripts/cron.sh >> grass-log.txt

      - name: git commit push
        run: |
          echo Begin to grow grass
          git config user.name "Takuya3627"
          git config user.email "tm.0630.ppp@gmail.com"
          git add .
          git commit -m "add log"
          git push origin master
